# Generated by Django 4.0.6 on 2022-08-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qrdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ewb_no', models.CharField(max_length=70)),
                ('ewb_date', models.CharField(max_length=70)),
                ('gen_date', models.CharField(max_length=70)),
                ('ewb_valid_till', models.CharField(max_length=70)),
                ('gen_by', models.CharField(max_length=70)),
            ],
        ),
    ]
